# Generated by Django 2.2.3 on 2020-02-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noName', max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=180, verbose_name='message')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
