# Generated by Django 2.2.3 on 2020-02-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('email', models.EmailField(max_length=254)),
                ('userCode', models.BigIntegerField(verbose_name='User Code')),
            ],
            options={
                'ordering': ['-username'],
            },
        ),
    ]
