# Generated by Django 2.2.3 on 2020-02-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='noName', max_length=20, verbose_name='name'),
        ),
    ]
