# Generated by Django 2.2.3 on 2020-02-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.CharField(max_length=100, verbose_name='User Code'),
        ),
    ]
