# Generated by Django 2.2.3 on 2020-02-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200217_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.CharField(default=' ', max_length=100, verbose_name='User Code'),
        ),
    ]
