# Generated by Django 2.2.3 on 2020-02-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
